### ISSUE TITLE
运行atx-webide，无法连接设备

### ISSUE THREAD

**Issue by zhjfeng** [openatx/atx-webide#33]
atx版本：1.1.3.dev3
atx-webide：版本0.1.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Python27\lib\site-packages\atxweb\server.py", line 374, in post
    info = device.info
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 616, in info
    return self.server.jsonrpc.deviceInfo()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 408, in jsonrpc
    return self.jsonrpc_wrap(timeout=int(os.environ.get("jsonrpc_timeout", 90)))
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 446, in jsonrpc_wrap
    return JsonRPCClient(self.rpc_uri,
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 549, in rpc_uri
    return "http://%s:%d/jsonrpc/0" % (self.adb.adb_server_host, self.local_port)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 381, in local_port
    raise RuntimeError("Error run: adb forward tcp:<any> tcp:%d" % self.device_port)
RuntimeError: Error run: adb forward tcp:<any> tcp:9008
ERROR:tornado.access:500 POST /device (127.0.0.1) 11725.00m

**Comment by ijasonyi** [comment]
试试pip install atx-webide==0.1.1.dev72

**Comment by zhjfeng** [comment]
0.1.1.dev72，用的就是这个版本
pip install atx-webide 安卓的是0.1.0的版本，报错上个人贴了~
