### ISSUE TITLE
MAC上安装失败

### ISSUE THREAD

**Issue by ghost62184** [openatx/atx-webide#34]
安装失败，报如下错误，有没有遇到的？
BenLis-iMac:atx-webide-master me$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    dist = setuptools.setup(setup_requires=['pbr'], pbr=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 221, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 825, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 837, in obtain
    return installer(requirement)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 294, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 598, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 628, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 823, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 1103, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 1089, in run_setup
    run_setup(setup_script, args)
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 78, in run
    return func()
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 22, in <module>
    
  File "/var/folders/74/pskvdm61323f0sx5xk_wz9t80000gr/T/easy_install-0h7Cf4/pbr-3.0.1/pbr/util.py", line 267, in cfg_to_args
  File "/var/folders/74/pskvdm61323f0sx5xk_wz9t80000gr/T/easy_install-0h7Cf4/pbr-3.0.1/pbr/util.py", line 576, in wrap_commands
  File "/Library/Python/2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2017, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/Library/Python/2.7/site-packages/sphinx/application.py", line 26, in <module>
    from docutils.parsers.rst import convert_directive_function, \
  File "/Library/Python/2.7/site-packages/docutils/parsers/rst/__init__.py", line 74, in <module>
    import docutils.statemachine
  File "/Library/Python/2.7/site-packages/docutils/statemachine.py", line 113, in <module>
    from docutils import utils
  File "/Library/Python/2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/Library/Python/2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/Library/Python/2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
BenLis-iMac:atx-webide-master me$

**Comment by ijasonyi** [comment]
这个没见过，是编码问题？
python setup.py install不是使用pip吗？

**Comment by ghost62184** [comment]
不清楚啊，我这个是下载源码安装的，使用pip安装也是报着错误。windows上装是可以的。
