### ISSUE TITLE
连接设备失败

### ISSUE THREAD

**Issue by liangliangludan** [openatx/atx-webide#35]
2017-06-20 17:36:24.812 INFO  [webide: 468] Server started.
2017-06-20 17:36:24.813 INFO  [webide: 469] Listening port on 127.0.0.1:10010
android device list: [u'8ab1d582']
WARNING:tornado.access:404 GET /$%7Bimg.path%7D?h=${img.hash} (127.0.0.1) 1.48ms
WARNING:tornado.access:404 GET /$%7Bimg.path%7D (127.0.0.1) 0.63ms
2017-06-20 17:36:25.653 INFO  [webide: 125] WebSocket connected
WARNING:tornado.access:404 GET /$%7Bimg.path%7D?h=${img.hash} (127.0.0.1) 0.89ms
WARNING:tornado.access:404 GET /$%7Bimg.path%7D (127.0.0.1) 0.66ms
http://127.0.0.1:10010/static/arrows_drag_horiz.png?v=cefb12fe29a2aba1fd732c86a3f4022cERROR:tornado.application:Uncaught exception POST /device (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:10010', method='POST', uri='/device', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:10010', 'Content-Length': '7', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:10010', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:10010/', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/Users/leoliang/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/leoliang/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/atxweb/server.py", line 373, in post
    device = atx.connect(**settings)
  File "/Users/leoliang/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/atx/__init__.py", line 77, in connect
    c = cls(connect_url, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'serialno'
ERROR:tornado.access:500 POST /device (127.0.0.1) 67.92ms

**Comment by clobob** [comment]
我也有相同的问题

**Comment by codeskyblue** [comment]
Fixed in new version of atx

```
pip install --pre --upgrade atx
```

**Comment by liangliangludan** [comment]
thanks for the new version
